/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'company' : string,
  'address' : string,
  'phoneNumber' : string,
}
export interface Proposal {
  'id' : bigint,
  'status' : ProposalStatus,
  'title' : string,
  'clientId' : bigint,
  'value' : bigint,
  'createdAt' : Time,
  'description' : string,
}
export type ProposalStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : Principal,
  'title' : string,
  'createdAt' : Time,
  'dueDate' : Time,
  'description' : string,
  'projectId' : [] | [bigint],
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProposal' : ActorMethod<[bigint, string, string, bigint], Proposal>,
  'createTask' : ActorMethod<[Principal, string, string, Time], Task>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllClientsSorted' : ActorMethod<[[] | [string]], Array<Client>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientsByCompany' : ActorMethod<[string, [] | [string]], Array<Client>>,
  'getOverdueTasks' : ActorMethod<[], Array<Task>>,
  'getProposalsByClient' : ActorMethod<[bigint], Array<Proposal>>,
  'getProposalsByClientAndStatus' : ActorMethod<
    [bigint, ProposalStatus],
    Array<Proposal>
  >,
  'getProposalsByStatus' : ActorMethod<[ProposalStatus], Array<Proposal>>,
  'getTaskStatusCount' : ActorMethod<[], Array<[TaskStatus, bigint]>>,
  'getTasksByAssignee' : ActorMethod<[Principal], Array<Task>>,
  'getTasksByAssigneeAndStatus' : ActorMethod<
    [Principal, TaskStatus],
    Array<Task>
  >,
  'getTasksByDueDateRange' : ActorMethod<[Time, Time], Array<Task>>,
  'getTasksByStatus' : ActorMethod<[TaskStatus], Array<Task>>,
  'getTasksByYear' : ActorMethod<[bigint], Array<Task>>,
  'getTasksCreatedByAssignee' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setProposalStatus' : ActorMethod<[bigint, ProposalStatus], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];