/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProposalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProposalStatus,
  'title' : IDL.Text,
  'clientId' : IDL.Nat,
  'value' : IDL.Nat,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'assignee' : IDL.Principal,
  'title' : IDL.Text,
  'createdAt' : Time,
  'dueDate' : Time,
  'description' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProposal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [Proposal],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, Time],
      [Task],
      [],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllClientsSorted' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Client)],
      ['query'],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientsByCompany' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(Client)],
      ['query'],
    ),
  'getOverdueTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getProposalsByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Proposal)], ['query']),
  'getProposalsByClientAndStatus' : IDL.Func(
      [IDL.Nat, ProposalStatus],
      [IDL.Vec(Proposal)],
      ['query'],
    ),
  'getProposalsByStatus' : IDL.Func(
      [ProposalStatus],
      [IDL.Vec(Proposal)],
      ['query'],
    ),
  'getTaskStatusCount' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TaskStatus, IDL.Nat))],
      ['query'],
    ),
  'getTasksByAssignee' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getTasksByAssigneeAndStatus' : IDL.Func(
      [IDL.Principal, TaskStatus],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getTasksByDueDateRange' : IDL.Func([Time, Time], [IDL.Vec(Task)], ['query']),
  'getTasksByStatus' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
  'getTasksByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getTasksCreatedByAssignee' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setProposalStatus' : IDL.Func([IDL.Nat, ProposalStatus], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProposalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProposalStatus,
    'title' : IDL.Text,
    'clientId' : IDL.Nat,
    'value' : IDL.Nat,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'assignee' : IDL.Principal,
    'title' : IDL.Text,
    'createdAt' : Time,
    'dueDate' : Time,
    'description' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProposal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [Proposal],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, Time],
        [Task],
        [],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllClientsSorted' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Client)],
        ['query'],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientsByCompany' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(Client)],
        ['query'],
      ),
    'getOverdueTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getProposalsByClient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getProposalsByClientAndStatus' : IDL.Func(
        [IDL.Nat, ProposalStatus],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getProposalsByStatus' : IDL.Func(
        [ProposalStatus],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getTaskStatusCount' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TaskStatus, IDL.Nat))],
        ['query'],
      ),
    'getTasksByAssignee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getTasksByAssigneeAndStatus' : IDL.Func(
        [IDL.Principal, TaskStatus],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getTasksByDueDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getTasksByStatus' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
    'getTasksByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getTasksCreatedByAssignee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setProposalStatus' : IDL.Func([IDL.Nat, ProposalStatus], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };